### ISSUE TITLE
Add to Stackage

### ISSUE THREAD

**Issue by 3noch** [dmjio/stripe#76]
This would get the library onto nixpkgs as well.

**Comment by ncaq** [comment]
It is not in lts-9.*.

I can not upgrade, so I am in trouble.

Even if you specify version 2.2.2 in the `extra-deps` record, the version of` aeson` does not match and installation can not be done.

As I looked at the `cabal` file now, there seems to be no problem with the version specification.

Is it slow to reflect on stackage?

I tried to make a pull request but I was not familiar with nix so I did not know how to do consistency with stack.

**Comment by ncaq** [comment]
It is not in lts-9.*.
I can not upgrade, so I am in trouble.

Even if you specify version 2.2.2 in the `extra-deps` record, the version of` aeson` does not match and installation can not be done.

Although I looked at the `cabal` file, it seems that there is no problem with version specification.

I tried to make a pull request but I was not familiar with nix so I did not know how to do consistency with stack.

I expect it.

Thanks.

**Comment by chreekat** [comment]
@dmjio anything I can do to help out here?

**Comment by chreekat** [comment]
Little status update .. 

My first step was to make sure tests still pass. For expediency I reran 'stack init' to get a relatively recent resolver, then tweaked some things to get builds working on NixOS, then ran the tests. I get one failure. So, right now the path to completing this issue is:

1. [ ] Fix test failure
2. [ ] Bump dependencies, dealing with any potential breaking changes (new versions of io-streams and time prevent stripe from building against the latest resolvers)
3. [ ] ???
4. [ ] Profit

I'll push a branch with my build tweaks.

The test failure is:

```
    Failures:

      tests/Web/Stripe/Test/Event.hs:15:
      1) Event tests Succesfully retrieves events
           predicate failed on: Left (StripeError {errorType = ParseFailure, errorMsg = "key \"evidence_due_by\" not present", errorCode = Nothing, errorParam = Nothing, errorHTTP = Nothing})

    Randomized with seed 85710200
```

That seems a bit odd, since it looks like a mismatch with Stripe's API. But the API version should have been fixed, right?

**Comment by chreekat** [comment]
There's the build/test branch. Never mind my force push :|

**Comment by dmjio** [comment]
https://github.com/fpco/stackage/pull/2942
